// pub mod gigasecond;
// pub mod rpn_calculator;
// pub mod assembly_line;
// pub mod health_statistics;
// pub mod low_power_embedded_game;
// pub mod magazine_cutout;
// pub mod resistor_color;
// pub mod reverse_string;
// pub mod role_playing_game;
// pub mod sublist;
// pub mod clock;
// pub mod anagram;
// pub mod space_age;
// pub mod minesweeper;
// pub mod luhn;
// pub mod parallel_letter_frequency;
// pub mod macros;
// pub mod poker;
// pub mod forth;
// pub mod armstrong_number;
// pub mod beer_song;
// pub mod difference_of_squares;
// pub mod grains;
// pub mod leap;
// pub mod nth_prime;
// pub mod prime_factors;
// pub mod proverb;
// pub mod raindrops;
// pub mod sum_of_multiples;
// pub mod bob;
// pub mod high_scores;
// pub mod matching_brackets;
// pub mod acronym;
// pub mod all_your_base;
// pub mod allergies;
// pub mod alphametics;
// pub mod binary_search;
// pub mod bowling;
// pub mod dot_dsl;
// pub mod etl;
// pub mod grade_school;
// pub mod collatz_conjecture;
// pub mod diffie_hellman;
// pub mod hamming;
// pub mod series;
// pub mod kindergarten_garden;
// pub mod eliuds_eggs;
//pub mod isbn_verifier;
//pub mod isogram;
//pub mod nucleotide_count;
//pub mod paas_io;
//pub mod palindrome_products;
//pub mod is_pangram;
//pub mod pascals_triangle;
//pub mod perfect_numbers;
//pub mod pig_latin;
//pub mod queen_attack;
//pub mod rna_transcription;
//pub mod run_length_encoding;
//pub mod saddle_points;
//pub mod say;
//pub mod scrabble_score;
//pub mod sieve;
pub mod simply_linked_list;
